language: generic

sudo: required

services:
  - docker

before-install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - docker build -t ehtesham/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ehtesham/docker-react npm run test