language: generic 

sudo: required

services:
  - docker

before-install:
  - docker build -t ehtesham/docker-react -f Dockerfile.dev .

script:
  - docker run ehtesham/docker-react npm run test -- --coverage